import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: "How clean is the code generated by AuraUI?",
      answer: "Extremely clean. The AI outputs structural, semantic React components using standard Tailwind utility classes. No random inline styles, no messy wrappers—just pure code as if a senior frontend engineer wrote it."
    },
    {
      question: "Can I use the components in commercial projects?",
      answer: "Yes, absolutely! Everything you generate with AuraUI comes with a full commercial license. You can use them for personal templates, client websites, or production SaaS platforms without any attribution."
    },
    {
      question: "Which frameworks are supported out of the box?",
      answer: "Currently, we fully support React and Next.js (TypeScript/JavaScript) optimized with Tailwind CSS. Vue and raw HTML/CSS styling generation features are rolling out shortly."
    },
    {
      question: "Is there a limit on how many components I can export?",
      answer: "The Free Starter plan gives you 10 credits per month to test things out. Upgrading to the Pro plan removes all restrictions, giving you unlimited layout generations and lightning-fast processing speeds."
    }
  ];

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="w-full bg-[#030303] py-24 px-6 md:px-12 lg:px-20 relative z-10 pointer-events-auto border-t border-white/[0.02]">
      <div className="max-w-4xl mx-auto">
        
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <span className="text-xs font-mono tracking-widest text-cyan-400 uppercase block mb-3">
            Questions & Answers
          </span>
          <h2 className="text-3xl md:text-4xl font-semibold tracking-tight text-white mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-sm text-zinc-400 font-light">
            Got questions about AuraUI? We've got answers.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.05 }}
                className={`border rounded-xl transition-colors duration-300 overflow-hidden ${
                  isOpen ? 'bg-white/[0.02] border-white/10' : 'bg-transparent border-white/5 hover:border-white/10'
                }`}
              >
                {/* FAQ Header Button */}
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between p-6 text-left cursor-pointer select-none"
                >
                  <span className="text-sm md:text-base font-medium text-white tracking-wide">
                    {faq.question}
                  </span>
                  <motion.div
                    animate={{ rotate: isOpen ? 180 : 0 }}
                    transition={{ duration: 0.2 }}
                    className={`text-zinc-400 ${isOpen ? 'text-cyan-400' : ''}`}
                  >
                    <ChevronDown size={18} />
                  </motion.div>
                </button>

                {/* FAQ Dynamic Answer Dropdown */}
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25, ease: "easeInOut" }}
                    >
                      <div className="px-6 pb-6 text-xs md:text-sm text-zinc-400 font-light leading-relaxed border-t border-white/[0.02] pt-4 bg-zinc-950/20">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default FAQ;